import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const robotoRoboto_Mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={cn(robotoRoboto_Mono.className, "p-10")}>
                <Toaster
                    richColors={true}
                    position="top-center"
                    theme="dark"
                    closeButton={true}
                />
                {children}
            </body>
        </html>
    );
}
