import { Toaster } from "@/components/ui/sonner";
import { fontPrimary, fontSecondary } from "@/constants/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";
import { NavigationBar } from "@/components/navigation/navigation-bar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark" suppressHydrationWarning>
            <body className={cn(fontPrimary.className, "relative p-20")}>
                <h1
                    className={cn(
                        fontSecondary.className,
                        "absolute left-5 top-5 text-4xl font-bold text-primary",
                    )}
                >
                    {"<"} Rajat Verma {"/>"}
                </h1>

                <NavigationBar />
                <Toaster
                    richColors={true}
                    position="top-center"
                    theme="dark"
                    closeButton={true}
                />
                {children}
            </body>
        </html>
    );
}
